// "use client";

import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
// import ScrollToTop from "./components/ScrollToTop";
import { Providers } from "./providers";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      {/* <body className={inter.className}> */}
      <body className="dark:bg-black">
      <Providers>

        <Header />
        {children}
        <Footer />
        {/* <ScrollToTop /> */}
      </Providers>
      </body>
    </html>
  );
}
